# Generated by Django 3.2 on 2021-12-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category_product', to='mainapp.Category', verbose_name='Категории'),
        ),
    ]
