# Generated by Django 3.2 on 2022-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='from_pxl',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='color',
            name='to_pxl',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
