# Generated by Django 3.2 on 2022-04-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20220421_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='frontend/images/')),
            ],
            options={
                'verbose_name': 'Картинки для основных категорий',
                'verbose_name_plural': 'Картинки для основных категорий',
            },
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет для полоски под меню', 'verbose_name_plural': 'Цвет для полоски под меню'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='from_pxl',
        ),
        migrations.RemoveField(
            model_name='color',
            name='to_pxl',
        ),
    ]
